### ISSUE TITLE
Docker standaloneDashboardURL not working

### ISSUE THREAD

**Issue by tanguy-a** [neo4j-labs/neodash#469]
## Guidelines

Hey first of all thanks for the work, it's a nice visualisation tool. 

Closest issue found: https://github.com/neo4j-labs/neodash/issues/308

- NeoDash version: X2.2.5
- Neo4j Database version: 5.3.0

**Steps to reproduce:**

I have a Neo4J database filled with some data. 

I am using a docker-compose to run everything. 

I created a dashboard on Neodash to visualise it. I exported the configuration with a .json.

I saved it to my public github repo, set the `standalone` to true, `standaloneDashboardURL` to dashboard's link. 

I stopped my docker container and deleted it `docker stop/rm container`, started the container again `docker-compose up` 

Here are the compose parameters:
```
  neodash:
    image: nielsdejong/neodash:2.2.5
    restart: on-failure
    container_name: neodash
    hostname: neo4j
    ports:
      - "5005:5005"
    volumes:
      - ./neo4j/data:/data
    environment:
      - ssoEnabled=false
      - standalone=true
      - standaloneProtocol=neo4j
      - standaloneHost=localhost
      - standalonePort=7687
      - standaloneDatabase=neo4j
      - standaloneDashboardURL=https://github.com/myPublicRepo.json 
```

**Expected behavior**

The dashboard from `standaloneDashboardURL` should load.

**Actual behavior**

The dashboard from `standaloneDashboardURL` does not load. I cannot see any warning or error message in the logs.
